### PR TITLE
add telemetry IPs

### PR DESCRIPTION
**Pull request by hinzigers**

### CODE REVIEW

**Comment by Synaxis** [comment]
Nice find

**Comment by W4RH4WK** [comment]
Thanks.

**Comment by hinzigers** [comment]
Infos over "MS IPs"
https://github.com/hinzigers/blacklists/blob/master/ms-telemetry-ips
Domains assimilated for PI-Hole
https://github.com/hinzigers/blacklists/blob/master/ms-telemetry-tracking

**Comment by beerisgood** [comment]
"sls.update.microsoft.com.nsatc.net":
[Enables connections to Windows Update](https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1709-non-enterprise-editions)

"wdcp.microsoft.com"
[If you turn off traffic for this endpoint, the device will not use Windows Defender Cloud-based Protection](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints)

"storeedgefd.dsx.mp.microsoft.com"
[If you turn off traffic for these endpoints, apps cannot be installed or updated from the Microsoft Store. Additionally, the Microsoft Store won't be able to revoke malicious apps and users will still be able to open them](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints)

"login.live.com"
[The following endpoint is used to authenticate a device. If you turn off traffic for this endpoint, the device will not be authenticated](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints)

"wdcpalt.microsoft.com"
[Used by Windows Defender Antivirus to provide cloud-delivered protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus)

"sls.update.microsoft.com"
[If you turn off traffic for these endpoints, the device will not be able to connect to Windows Update and Microsoft Update to help keep the device secure](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints)

I don't know if you know what you're blocking, but that make Windows unsecure and unusable and none of them are telemetry domains

**Comment by hinzigers** [comment]
@beerisgood 
Yeah, I know what I'm deactivating. You don't know what you are activating. You quote Microsoft?! Are you serious? Defender works!

sls.update.microsoft* works even before Windows is fully installed and before cortana lies to you during the installation when it says; "we are now preparing the network connection".

Are you from Microsoft? Or do you just not know what you are writing?

To the blocklists: Blocklists contain domains that not everyone will need. That's normal. There are whitelists for that.

**Comment by beerisgood** [comment]
@W4RH4WK any statement on hinzigers post?

**Comment by W4RH4WK** [comment]
Honestly, I don't really have a strong opinion on this one.

Bringing back to mind that this repository is aimed at system administrator, knowing what they are doing, the block list seems like a non-essential part. I guess most administrators will have there own list which is probably enforced by network firewalls.

So, I am only concerned about picking *sane defaults*. From my point of view, I deem security more important than blocking telemetry. That said, I am no fan of Windows Defender nor the Windows Store.

Looking at the domains @beerisgood listed:
Most are still part of the current block list, as the PR got merged. However, `storeedgefd.dsx.mp.microsoft.com` was reported to break usage of the Windows Store in #173. This aligns with the sources provided.

After all, I'd rather base my decision on *credible* sources available to everyone. Therefore, I'll comment out the domains mentioned by @beerisgood so they are not blocked by default.

In case you may be wondering, do I trust Microsoft / view them as a credible source of information. This depends on a lot of factors and I'll judge that on a case-by-case basis. In this context, I trust their documentation more than some random dude on the internet I know nothing about. If you don't trust Microsoft even this far, better stay away from Windows entirely.

**Comment by hinzigers** [comment]
I would like to apologize. This mail account was not accessible to me. I 
agree. Of course, only take things that do not cause problems.

I fight in DE against the regime in Berlin. Currently no time for IT.

best regards

Am 21.02.19 um 16:32 schrieb Alex Hirsch:
>
> Honestly, I don't really have a strong opinion on this one.
>
> Bringing back to mind that this repository is aimed at system 
> administrator, knowing what they are doing, the block list seems like 
> a non-essential part. I guess most administrators will have there own 
> list which is probably enforced by network firewalls.
>
> So, I am only concerned about picking /sane defaults/. From my point 
> of view, I deem security more important than blocking telemetry. That 
> said, I am no fan of Windows Defender nor the Windows Store.
>
> Looking at the domains @beerisgood <https://github.com/beerisgood> listed:
> Most are still part of the current block list, as the PR got merged. 
> However, |storeedgefd.dsx.mp.microsoft.com| was reported to break 
> usage of the Windows Store in #173 
> <https://github.com/W4RH4WK/Debloat-Windows-10/issues/173>. This 
> aligns with the sources provided.
>
> After all, I'd rather base my decision on /credible/ sources available 
> to everyone. Therefore, I'll comment out the domains mentioned by 
> @beerisgood <https://github.com/beerisgood> so they are not blocked by 
> default.
>
> In case you may be wondering, do I trust Microsoft / view them as a 
> credible source of information. This depends on a lot of factors and 
> I'll judge that on a case-by-case basis. In this context, I trust 
> their documentation more than some random dude on the internet I know 
> nothing about. If you don't trust Microsoft even this far, better stay 
> away from Windows entirely.
>

**Comment by Znih** [comment]
> @hinzigers
> 
> "sls.update.microsoft.com.nsatc.net": [Enables connections to Windows Update](https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1709-non-enterprise-editions)
> 
> "wdcp.microsoft.com" [If you turn off traffic for this endpoint, the device will not use Windows Defender Cloud-based Protection](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints)
> 
> "storeedgefd.dsx.mp.microsoft.com" [If you turn off traffic for these endpoints, apps cannot be installed or updated from the Microsoft Store. Additionally, the Microsoft Store won't be able to revoke malicious apps and users will still be able to open them](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints)
> 
> "login.live.com" [The following endpoint is used to authenticate a device. If you turn off traffic for this endpoint, the device will not be authenticated](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints)
> 
> "wdcpalt.microsoft.com" [Used by Windows Defender Antivirus to provide cloud-delivered protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus)
> 
> "sls.update.microsoft.com" [If you turn off traffic for these endpoints, the device will not be able to connect to Windows Update and Microsoft Update to help keep the device secure](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints)
> 
> I don't know if you know what you're blocking, but that make Windows unsecure and unusable and none of them are telemetry domains

MS Windoof sollte nie durch Update sicherer werden, das war nur für die dummen Käufer. Sicher ist wie oben und unsicher bist du.

<video src="https://github.com/user-attachments/assets/51a1c58a-8a1d-4147-b9e9-30049d5e174a" controls="controls" style="max-width: 730px;"></video>

[sta-kl.webm](https://github.com/user-attachments/assets/4fe3c1e5-fb5d-49ff-ae52-5a3cb253bb4b)

**Comment by Znih** [comment]
> @W4RH4WK any statement on hinzigers post?

YES here @beerisgood 

https://github.com/W4RH4WK/Debloat-Windows-10/pull/146#issuecomment-2612386356

**Pull request merged**
