### PR TITLE
Don't remove Microsoft Edge.

### PR DESCRIPTION
**Pull request by JonathanWolfe**
Should actually be promoting this feature since it's what's going to replace IE going forward.

### CODE REVIEW

**Comment by MeltedLux** [comment]
:-1: the users of the script can comment out what they dont want removed.

**Comment by W4RH4WK** [comment]
Isn't Edge the new *feature* which will be replacing IE. Edge still seems to work after disabling `Internet-Explorer-Optional-amd64`. Edge can still be removed via that Windows app stuff.

I want to leave Edge intact by default so the user does not end up without a browser + I do not want to make a decision for them whether to use Firefox, Chrome, Opera, ... even though they can (and should) change the scripts.

**Comment by tumpio** [comment]
Yep, and this reads in the script's description as well:
> If you do not want to disable certain features comment out the corresponding lines below.

I was also thinking in #1 about providing interactive choices for these kind of scripts.

**Comment by W4RH4WK** [comment]
In general I do not want the scripts to be interactive. A `-Revert` flag sounds reasonable to me but for more interactive features use a GUI tool.

**Comment by JonathanWolfe** [comment]
I agree @MeltedLux, but I also think sensible defaults should be used like with `install-basic-stuff` and other scripts.

Maybe instead of deleting this line, I should just comment it out, @W4RH4WK?

**Comment by W4RH4WK** [comment]
@JonathanWolfe I'd comment the line out but to me it seems like Edge still works fine after removing the feature in question. Therefore I'd first like to know what exactly do I loose by removing this feature.

**Comment by JonathanWolfe** [comment]
@W4RH4WK a google search says it's actually IE11.

Can somebody who's run that command confirm?

**Comment by W4RH4WK** [comment]
Really?! Win10 ships with Edge and IE11 but Powershell's `wget` does not work.

**Comment by JonathanWolfe** [comment]
Yeah, I had assumed because of the `optional` part of the package name that it was Edge (considering it's the new *optional* browser), but it's actually `optional` because Win10 is based on Windows Server where IE is *optional*.

Also, `wget`? Why not ship with `curl` installed?

**Comment by W4RH4WK** [comment]
`wget` is just an alias for `Invoke-WebRequest` which is a built-in Powershell command. In Win7 it worked fine out-of-the-box but in Win10 it throws an error (I haven't looked into yet). I was required to get a web-client object from dotNet to simple download a file. Speaking of it I should probably put that code in a module and override the alias for now. Sounds like a good plan for tonight if the weather allows it.

**Comment by W4RH4WK** [comment]
Closing this issue since Edge still works after removing this feature from Windows.

**Pull request closed without merging**
