### PR TITLE
Win 10 home issues 

### PR DESCRIPTION
**Pull request by Carol666uk**
OK now I know I can post comment here I see you're German and when Germans do things they're done perfect and there are issues in your script:) 

1 remove quick access doesn't work after running script toolbar dissappear and have to restart win ctrl alt delete and when back quick access is still in Explorer

2 removing core apps you normally can't remove cortana defender and those few others,  did everything as you said and I'm getting errors one ps says doesn't have permission to change registry keys and then line come where dism says error 5 access denied

### CODE REVIEW

**Comment by W4RH4WK** [comment]
Hi Carol and welcome to Github (saw you created your account recently). I'll look into these issues, can you confirm that these problems *only* occur with the Win 10 Home edition?

Btw I am from Austria not Germany ;)  guess that's the reason my scripts are not perfect yet.

**Comment by Carol666uk** [comment]
Isn't Austria part of Germany?  I think somewhere up south of Germany right?  :)  just kidding :) 

I only have home edition win 10 and tried to remove cortana and edge and everything else and first part of that script worked perfectly the second part where was cortana edge defender located didn't work.  Plus quick access didn't work and onedrive didn't work either.

**Comment by Carol666uk** [comment]
And want to add your scripts are  really good and you're doing great work helping people clean their pcs of Microsofts crapware :)

**Comment by Carol666uk** [comment]
I want to ask because of I'm newbie and you know about those things much more.  In folder called systemapps I manually removed everything leaving microsoftsaccountcontrol and shellexperiencehost.  Did I remove to much from that folder. ?

**Comment by W4RH4WK** [comment]
Removing stuff from the systemapps folder is nearly the same as the script does. The script uses a more *official* way of doing this via `dism.exe`. I haven't tested the scripts with the Home edition yet, so I'll do this soon.

Thanks for letting me know. In general you should be creating a new "Issue" for questions or reporting such issues. The pull-request mechanism is there the "extend the code base".

**Comment by Carol666uk** [comment]
Microsoft.ADD.BrookerPlugin do you know what is it repose for? 
Also Microsoft.LockApp 
And Microsoft.BioEnrolment I have removed those jus not sure if I should ;)

**Comment by Carol666uk** [comment]
Ups and Microsoft .Windows.ContentDeliveryManager  removed it too

**Comment by W4RH4WK** [comment]
I am not that affiliated with Microsoft's service / components inside Windows I'd rather have you google that for your self. The BioEnrolment stuff is used for finger print login and so on. All that stuff that deals with you biometrics if I recall correctly.

**Comment by Carol666uk** [comment]
Tried to Google but nothing came up

**Comment by Carol666uk** [comment]
Only learned on my skin about shellexperience removed that one and lost icons on the taskbar ;)

**Comment by Carol666uk** [comment]
Just found a few things from Microsoft website you could add in your script if possible Microsoft.ADD.BrookerPlugin responsible for keeping kernel stable at least that's what they say Windows.ContentDeliveryManager responsible for ads, Microsoft.BioEnrolment also called hello face unlock, Microsoft.LockApp responsible for lock screen,  not sure what exactly for as I deleted it and my lock screen still works. that's what they said not even sure if to trust them Microsoft lol

**Comment by W4RH4WK** [comment]
I don't trust them anyway :p . Mainly using Linux ^^

**Comment by W4RH4WK** [comment]
I am sorry to tell you, but I wasn't able to reproduce this bug. The scripts in question did not throw any error on my Windows 10 Home installation.

**Comment by W4RH4WK** [comment]
Since you had a similar problem this may be solved for you too with issue #37.

**Comment by Carol666uk** [comment]
I have reinstalled windows 10 home,  and used 0.4 scripts and everything worked perfect.  The only apps that couldn't get rid of was edge,  cortana and I think contact support.  Removed them manually :)

**Comment by W4RH4WK** [comment]
You have to remove the `#` symbol before the entries regarding edge and Cortana. I do not remove edge by default since you would end up without any browser. Removing the Cortana package will break startmenu search, therefore this isn't removed by default either.

**Comment by Carol666uk** [comment]
I did remove # and I think part of cortana was removed because in start menu was only a link,  it wasn't fully removed like other apps as in sysapps there still was cortana folder 

Edge didn't uninstall at all 


And either customer support or feedback or something else didn't uninstall I forgot what it was :)  

It doesn't matter script is still great

**Comment by Carol666uk** [comment]
After removing defender there's remaining defender folder in data which is over 500mb fat :)  just saying in case someone wanted free 500mb

**Comment by W4RH4WK** [comment]
oh, removing that folder would be a great idea. i'll look into the other removal stuff later on, thanks

**Comment by W4RH4WK** [comment]
Some people said they have issues regarding windows updates after removing that ~ 500mb folder. I'll better leave it as it is.

**Pull request closed without merging**
