### PR TITLE
Add apps from creators update

### PR DESCRIPTION
**Pull request by tumpio**
Adding few apps that are included in the Creators update. There were more of them but I already removed many by hand. 

All of the mixed reality / HoloLens related apps are system apps and can't be removed by user. Same for the Miracast View and the new Security Health app. I added these to the experimental script and did not even try to remove them.

### CODE REVIEW

**Comment by majkinetor** [comment]
There is also duolingo

**Comment by tumpio** [comment]
Didn't have that one but feel free to add it. Are you sure it came with Creators Update?

**Comment by tumpio** [comment]
Found this another way of removing those locked apps for those who are interested:
http://alexappleton.net/post/159702702033/windows-10-pro-remove-wireless-display-media

This method allows to remove them using `Remove-AppxPackage`. It is possible to edit the database that stores the values if an app is a system app. The database is in "C:\ProgramData\Microsoft\Windows\AppRepository\StateRepository-Machine.srd" and the value to edit is `IsInbox`.

Editing the database requires system account permission.

**Comment by W4RH4WK** [comment]
I thought about modifying that SQLite db via a powershell script, but ditched the idea in the past since it seemed not worth the effort. Guess I'll need to reconsider that now.

**Pull request merged**
