### PR TITLE
Removed Windows Defender tray icon

### PR DESCRIPTION
**Pull request by majkinetor**

### CODE REVIEW

**Comment by W4RH4WK** [comment]
Why is this necessary if the script already disables Windows Defender via GP?

**Comment by W4RH4WK** [comment]
I removed the line killing the tray / GUI process since it is recommended to restart the computer after running the scripts. In the current version neither the Windows Defender Services, nor the GUI stuff should start.

Thanks for the input.

**Comment by majkinetor** [comment]
I still had the icon after i run all the scripts...

**Comment by W4RH4WK** [comment]
Note that with current version i referred to the changes I made just before merging this PR. Also note the addition to the README about rebooting, running `disable-windows-defender.ps1` again and rebooting another time.

**Pull request merged**
