### PR TITLE
force-mkdir.psm1 changed to New-FolderForced.psm1

### PR DESCRIPTION
**Pull request by Zoran-Jankov**
Changed `force-mkdir.psm1` to New-FolderForced.psm1 to uphold PowerShell conventions. Also added in all scripts to `Set-ItemProperty` and `New-ItemProperty` parameter `-Path` instead of implicitly using the -path parameter. No functionality is changed or affected.

### CODE REVIEW

**Comment by W4RH4WK** [comment]
Looks good, thank you.

**Comment by Zoran-Jankov** [comment]
@W4RH4WK Thank you for accepting my pull request. If you are interested I could refactor all scripts to be more compact, readable, and to follow PowerShell conventions to the letter.

**Comment by W4RH4WK** [comment]
Thank you for that offer. However, I'd rather decline. Even if the changes look trivial, I have to go over them line by line to ensure nothing bad or malicious code is introduced (no offense).

Also, while it would probably be more pleasing to look at the code that way. I am certain there are better things to spend your valuable time on than polishing this non-professional project.

**Comment by W4RH4WK** [comment]
Thanks for pointing that out. Just fixed it.

I guess you see my point. Even reviewing your commit prior merging, these things slip through.

**Pull request merged**
