### PR TITLE
Update remove-onedrive.ps1

### PR DESCRIPTION
**Pull request by narutards**
Getting rid of the Registry-Helper where easily possible to slimline the script

### CODE REVIEW

**Comment by W4RH4WK** [comment]
The registry key `HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\OneDrive` does not exist by default. Guess you have to first create the registry key and than add the property using `New-ItemProperty`

**Comment by narutards** [comment]
My bad. Add the following line above the Set-ItemProperty line:

New-Item -Path 'HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\OneDrive\'

"Set-ItemProperty" can also be used if the property doesnt exist yet, so there is no Need to explicitly use "New-ItemProperty".

**Comment by narutards** [comment]
Oh, and personally I like the New-Item/Set-ItemProperty bit way better than having to rely on external libs. With the external lib you cant just take the powershell script by itself and execute it somewhere. You always have to "carry around" the complete archive.

**Comment by W4RH4WK** [comment]
I agree with that, but the main purpose for the lib was the `Takeown-Registry` command together with `Elevate-Privileges`. I think Powershell should have an import commandlet by default. My import command is a shameless hack.

**Comment by narutards** [comment]
I've improved it a bit more so it doesnt fail anymore if the key already exists.

if (-Not (Get-Item -Path 'HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\OneDrive\' -ErrorAction SilentlyContin)) {
  New-Item -Path 'HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\OneDrive\'
}

**Comment by W4RH4WK** [comment]
Can you update your branch so I can merge the latest version. Also for #19.

**Comment by narutards** [comment]
I might have done it. Maybe. Possibly... Github webinterface is quite confusing. -.-

**Comment by W4RH4WK** [comment]
Nope does not seem so. You just have to push to *your* `patch-2` branch on *your* forked repository. The pull-request will automatically update with your branch

**Pull request merged**
