### PR TITLE
Prefetch/Prelaunch

### PR DESCRIPTION
**Pull request by ogmios-voice**

### CODE REVIEW

**Comment by beerisgood** [comment]
You know that you reduce the whole system performance, doesn't you?

**Comment by ogmios-voice** [comment]
Only if you are not using an SSD. But if your programs are stored on one -- it doesn't even need to be an M.2 PCIe SSD --, it is suggested to turn these off.
The usage pattern is also relevant: if you are opening and closing different type of documents every few minutes, then you will benefit from Prefetch (on a harddisk), but if you are playing, or developing (working for hours with the same tools), then it will just keep in the memory (or even worse: in the swap file) things you don't use.

**Comment by beerisgood** [comment]
Who suggest that?
Microsoft not and i guess they know their system better then others. And yes, Windows know if you use a SSD or HDD.

Also your argument may valid for devs but i would say they don't use this project. But normal users do.
I would recommend Windows defaults for that

**Comment by ogmios-voice** [comment]
Well, I do use this project... and I'm not a normal user.

_"In short SuperFetch and Prefetch are Windows Storage Management technologies that provide fast access to data on traditional hard drives. On Solid State Drives they result in unnecessary write operations."_
("Who suggest that?": _"Posted by AnandK@TWC on April 4, 2013 , in Category Windows with Tags Features, SSD, Tips. Anand Khanse is the Admin of TheWindowsClub.com, a 10-year Microsoft MVP Awardee in Windows (2006-16) & a Windows Insider MVP"_)
https://www.thewindowsclub.com/disable-superfetch-prefetch-ssd
(note: Superfetch in the meanwhile was renamed to SysMain, and it is required also for RAM Compression.)

_"**Prefetch** will actually re-arrange data on a **hard disk** so it loads faster. It is not a cache. [...] Prefetch, on the other hand, is more a "tactical" tool for "immediate" impact. It is used to optimize the loading time of an application the very next time you run it. This would be great for large applications like Microsoft Word or your security programs where multiple large files are loaded each time Word or Windows starts."_
https://www.techpowerup.com/forums/threads/prefetch-superfetch-sysmain-ready-boost-levels-of-cache.250875/

_"when these features were created, 99% of computers had platter type **hard drives** in them (HDD’s). HDD’s were much slower than modern SSD’s, especially when reading files spread all over the drive. By putting the files you needed at startup in one place, **Prefetch** could significantly speedup the boot process because commonly loaded files could be read one after the other from that one place."_
https://www.lovemysurface.net/prefetch-and-superfetch/

**Pull request merged**
