### PR TITLE
SSD tuning

### PR DESCRIPTION
**Pull request by ogmios-voice**

### CODE REVIEW

**Comment by beerisgood** [comment]
Why do that?

"DisableLastAccess" remove a feature a lot people use, i would say 
Disable "EncryptPagingFile" reduce security - if Bitlocker is activated at all.

Also a SSD have good performance. No need to such "pro" tweaks

**Comment by ogmios-voice** [comment]
If someone is using last access time, obviously he/she shouldn't disable that feature. But I barely know anyone really using it (including software developers and devops). Actually I don't even know the default settings for this, so it might be already turned off on a fresh system.
Still no operating system should enforce on you extra resource consumption (and not only because based on how SSDs write to the flash, this will reduce the lifespan of your drive).

**Comment by beerisgood** [comment]
Nowadays SSDs doesn't have a lifespan problem anymore.

So why did you disable features if you don't know if they're disabled or not already?
Doesn't sound serious for me

**Comment by W4RH4WK** [comment]
Hey @ogmios-voice, do you have any additional sources you can link to regarding this. Ideally I am looking for a detailed explanation what those switches do (including their consequences) or a benchmark illustrating the benefit of this tweak.

For the last 5 or so years I didn't even bother tweaking any SSD related settings and haven't had a problem ever since.

**Comment by ogmios-voice** [comment]
`DisableLastAccess`: I'm using this tweak for quite a while, this is why I didn't know its current default value (hopefully they won't change it back again):
_"They aren't turned off to save space, but rather because it results in an **unnecessary amount of writes** when you are reading a large number of files. [...] On **Vista** systems **and later**, access times are [disabled by default](http://forensicswiki.org/wiki/MAC_times#Access_Time_Update) via a default registry value of 1 for `NtfsDisableLastAccessUpdate`."_
https://security.stackexchange.com/questions/52100/external-hard-drives-date-last-accessed-file

`EncryptPagingFile`: _"Encrypting the pagefile prevents malicious users from reading data that has been paged to disk, but also adds **processing overhead** for filesystem operations."_ 
https://www.tenforums.com/tutorials/77782-enable-disable-virtual-memory-pagefile-encryption-windows-10-a.html

**Pull request merged**
